export const fage1e = {
  Accuracy: [
    "Arcane Blast",
    "Black Powder",
    "Bows",
    "Brawling",
    "Dueling",
    "Grenades",
    "Light Blades",
    "Slings",
    "Staves",
  ],
  Communication: [
    "Animal Handling",
    "Bargaining",
    "Deception",
    "Disguise",
    "Etiquette",
    "Gambling",
    "Investigation",
    "Leadership",
    "Performing",
    "Persuasion",
    "Seduction",
  ],
  Constitution: ["Rowing", "Running", "Stamina", "Swimming", "Tolerance"],
  Dexterity: [
    "Acrobatics",
    "Calligraphy",
    "Crafting",
    "Initiative",
    "Legerdemain",
    "Lock Picking",
    "Riding",
    "Sailing",
    "Stealth",
    "Traps",
  ],
  Fighting: [
    "Axes",
    "Bludgeons",
    "Heavy Blades",
    "Lances",
    "Polearms",
    "Spears",
  ],
  Intelligence: [
    "Arcana",
    "Arcane Lore",
    "Brewing",
    "Cartography",
    "Cryptography",
    "Cultural Lore",
    "Engineering",
    "Evaluation",
    "Healing",
    "Heraldry",
    "Historical Lore",
    "Military Lore",
    "Musical Lore",
    "Natural Lore",
    "Navigation",
    "Religious Lore",
    "Research",
    "Thieves’ Lore",
    "Writing",
  ],
  Perception: [
    "Empathy",
    "Hearing",
    "Searching",
    "Seeing",
    "Smelling",
    "Tasting",
    "Touching",
    "Tracking",
  ],
  Strength: [
    "Climbing",
    "Driving",
    "Intimidation",
    "Jumping",
    "Might",
    "Smithing",
  ],
  Willpower: ["Courage", "Faith", "Morale", "Self-Discipline"],
};

export const fage2e = {
  Accuracy: [
    "Arcane Blast",
    "Black Powder",
    "Bows",
    "Brawling",
    "Dueling",
    "Grenades",
    "Light Blades",
    "Slings",
    "Staves",
  ],
  Communication: [
    "Animal Handling",
    "Bargaining",
    "Deception",
    "Disguise",
    "Etiquette",
    "Gambling",
    "Investigation",
    "Leadership",
    "Performing",
    "Persuasion",
    "Seduction",
  ],
  Constitution: ["Rowing", "Running", "Stamina", "Swimming", "Tolerance"],
  Dexterity: [
    "Acrobatics",
    "Calligraphy",
    "Crafting",
    "Initiative",
    "Legerdemain",
    "Lock Picking",
    "Riding",
    "Sailing",
    "Stealth",
    "Traps",
  ],
  Fighting: [
    "Axes",
    "Bludgeons",
    "Heavy Blades",
    "Lances",
    "Polearms",
    "Spears",
  ],
  Intelligence: [
    "Arcana",
    "Arcane Lore",
    "Brewing",
    "Cartography",
    "Cryptography",
    "Cultural Lore",
    "Engineering",
    "Evaluation",
    "Healing",
    "Heraldry",
    "Historical Lore",
    "Military Lore",
    "Musical Lore",
    "Natural Lore",
    "Navigation",
    "Religious Lore",
    "Research",
    "Thieves’ Lore",
    "Writing",
  ],
  Perception: [
    "Empathy",
    "Hearing",
    "Searching",
    "Seeing",
    "Smelling",
    "Tasting",
    "Touching",
    "Tracking",
  ],
  Strength: [
    "Climbing",
    "Driving",
    "Intimidation",
    "Jumping",
    "Might",
    "Smithing",
  ],
  Willpower: ["Courage", "Faith", "Morale", "Self-Discipline"],
};

export const mage = {
  Accuracy: [
    "Assault Rifles",
    "Black Power",
    "Bows",
    "Grenades",
    "Longarms",
    "Pistols",
    "Shotguns",
    "SMGs",
    "Thrown",
    "Unarmed",
  ],
  Communication: [
    "Animal Handling",
    "Bargaining",
    "Deception",
    "Disguise",
    "Etiquette",
    "Expression",
    "Gambling",
    "Investigation",
    "Leadership",
    "Performing",
    "Persuasion",
    "Seduction",
  ],
  Constitution: ["Propelling", "Running", "Stamina", "Swimming", "Tolerance"],
  Dexterity: [
    "Acrobatics",
    "Calligraphy",
    "Crafting",
    "Initiative",
    "Legerdemain",
    "Lock Picking",
    "Riding",
    "Sailing",
    "Stealth",
    "Traps",
  ],
  Fighting: [
    "Brawling",
    "Flexible Weapons",
    "Grappling",
    "Heavy Blades",
    "Light Blades",
    "Long Hafterd",
    "Short Hafted",
  ],
  Intelligence: [
    "Anthropology",
    "Art",
    "Astronomy",
    "Biology",
    "Business",
    "Cartography",
    "Chemistry",
    "Computers",
    "Cryptography",
    "Current Affiars",
    "Earth Siciences",
    "Engineering",
    "Electronics",
    "Evaluation",
    "History",
    "Homemaking",
    "Law",
    "Medicine",
    "Navigation",
    "Occultism",
    "Physics",
    "Research",
    "Security",
    "Tactics",
    "Theology",
    "Tinkering",
  ],
  Perception: [
    "Empathy",
    "Hearing",
    "Searching",
    "Seeing",
    "Smelling",
    "Tasting",
    "Touching",
    "Tracking",
  ],
  Strength: [
    "Climbing",
    "Intimidation",
    "Jumping",
    "Machining",
    "Might",
    "Steering",
  ],
  Willpower: ["Courage", "Faith", "Morale", "Self-Discipline"],
};

export const cthulhu = {
  Accuracy: [
    "Arcane Blast",
    "Black Powder",
    "Bows",
    "Brawling",
    "Dueling",
    "Grenades",
    "Light Blades",
    "Slings",
    "Staves",
  ],
  Communication: [
    "Animal Handling",
    "Animism",
    "Bargaining",
    "Deception",
    "Disguise",
    "Etiquette",
    "Gambling",
    "Investigation",
    "Leadership",
    "Performance",
    "Persuasion",
    "Psychic",
    "Romance",
  ],
  Constitution: ["Drinking", "Rowing", "Running", "Stamina", "Swimming"],
  Dexterity: [
    "Acrobatics",
    "Artisan",
    "Calligraphy",
    "Crafting",
    "Initiative",
    "Legerdemain",
    "Lock Picking",
    "Riding",
    "Sailing",
    "Stealth",
    "Traps",
  ],
  Fighting: ["Axes", "Bludgeons", "Heavy Blades", "Lances", "Polearms"],
  Intelligence: [
    "Arcana",
    "Arcane Lore",
    "Brewing",
    "Cartography",
    "Cryptography",
    "Cultural Lore",
    "Engineering",
    "Evaluation",
    "Healing",
    "Heraldry",
    "Historical Lore",
    "Military Lore",
    "Musical Lore",
    "Natural Lore",
    "Navigation",
    "Religious Lore",
    "Research,Thieves’ Lore",
    "Writing",
  ],
  Perception: [
    "Empathy",
    "Hearing",
    "Searching",
    "Seeing",
    "Smelling",
    "Tasting",
    "Touching",
    "Tracking",
  ],
  Strength: [
    "Climbing",
    "Driving",
    "Intimidation",
    "Jumping",
    "Might",
    "Smithing",
  ],
  Willpower: ["Courage", "Faith", "Morale", "Self-Discipline"],
};

export const bluerose = {
  Accuracy: ["Arcane", "Bows", "Brawling", "Light Blades", "Staves"],
  Communication: [
    "Animal Handling",
    "Animism",
    "Bargaining",
    "Deception",
    "Disguise",
    "Etiquette",
    "Gambling",
    "Investigation",
    "Leadership",
    "Performance",
    "Persuasion",
    "Psychic",
    "Romance",
  ],
  Constitution: ["Drinking", "Rowing", "Running", "Stamina", "Swimming"],
  Dexterity: [
    "Acrobatics",
    "Calligraphy",
    "Crafting",
    "Initiative",
    "Legerdemain",
    "Lock Picking",
    "Riding",
    "Sailing",
    "Stealth",
    "Traps",
  ],
  Fighting: ["Axes", "Bludgeons", "Heavy Blades", "Lances", "Polearms"],
  Intelligence: [
    "Arcane Lore",
    "Brewing",
    "Cartography",
    "Cryptography",
    "Cultural Lore",
    "Engineering",
    "Evaluation",
    "Healing",
    "Heraldry",
    "Historical Lore",
    "Military Lore",
    "Musical Lore",
    "Natural Lore",
    "Nautical Lore",
    "Navigation",
    "Religious Lore",
    "Remote Weapons",
    "Research",
    "Shaping",
    "Sorcery Lore",
    "Writing",
  ],
  Perception: [
    "Empathy",
    "Hearing",
    "Searching",
    "Seeing",
    "Smelling",
    "Tasting",
    "Touching",
    "Tracking",
  ],
  Strength: [
    "Climbing",
    "Driving",
    "Intimidation",
    "Jumping",
    "Might",
    "Smithing",
  ],
  Willpower: [
    "Courage",
    "Faith",
    "Meditative",
    "Morale",
    "Purity",
    "Self-Discipline",
  ],
};

export const expanse = {
  Accuracy: ["Bows", "Gunnery", "Pistols", "Rifles", "Throwing"],
  Communication: [
    "Bargaining",
    "Deception",
    "Disguise",
    "Etiquette",
    "Expression",
    "Gambling",
    "Investigation",
    "Leadership",
    "Performing",
    "Persuasion",
    "Seduction",
  ],
  Constitution: ["Running", "Stamina", "Swimming", "Tolerance"],
  Dexterity: [
    "Acrobatics",
    "Crafting",
    "Driving",
    "Free-fall",
    "Initiative",
    "Piloting",
    "Sleight of Hand",
    "Stealth",
  ],
  Fighting: ["Brawling", "Grappling", "Heavy Weapon", "Light Weapons"],
  Intelligence: [
    "Art",
    "Business",
    "Cryptography",
    "Current Affairs",
    "Demolitions",
    "Engineering",
    "Evaluation",
    "Law",
    "Medicine",
    "Navigation",
    "Research",
    "Science",
    "Security",
    "Tactics",
    "Technology",
  ],
  Perception: [
    "Empathy",
    "Hearing",
    "Intuition",
    "Searching",
    "Seeing",
    "Smelling",
    "Survival",
    "Tasting",
    "Touching",
    "Tracking",
  ],
  Strength: ["Climbing", "Intimidation", "Jumping", "Might"],
  Willpower: ["Courage", "Faith", "Self-Discipline"],
};
