import { writeFileSync } from 'fs';
import { join } from 'path';
import { SheetHydrateSchema } from '@/schemas/hydrate/sheet';
import { discoverEffectCollections } from '@/system/effects/discoverEffectCollections';

try {
  const paths = discoverEffectCollections(SheetHydrateSchema);

  const content = `// This file is auto-generated by scripts/generate-effect-paths.ts.
// Do not edit this file directly.

export const effectCollectionPaths = ${JSON.stringify(paths, null, 2)} as const;
`;

  const outputPath = join(process.cwd(), 'src/system/effects/generatedEffectPaths.ts');
  writeFileSync(outputPath, content, 'utf-8');
  console.log(`[generate-effect-paths] Generated ${paths.length} paths to ${outputPath}`);
} catch (error) {
  console.error('[generate-effect-paths] Error generating paths:', error);
  process.exit(1);
}
