// This file is auto-generated by scripts/generate-effect-paths.ts.
// Do not edit this file directly.

export const effectCollectionPaths = [
  "sample.effects",
  "effects.effects",
  "powers.list[*].effects",
  "powers.list[*].modifiers[*].effects",
  "combat.criticalInjuries[*].effects",
  "features.list[*].effects",
  "gear.list[*].effects"
] as const;
