import type { ActionItem } from '@/schemas/hydrate/actions';

export const DEFAULT_ACTIONS: ActionItem[] = [
  
  {
    _id: 'full-slugfest',
    name: 'Slugfest attack',
    type: 'full',
    attributeUsed: 'fighting',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-charge',
    name: 'Charge attack',
    type: 'full',
    attributeUsed: 'strength',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-shooting',
    name: 'Shooting attack',
    type: 'full',
    attributeUsed: 'agility',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-use_power',
    name: 'Use a power',
    type: 'full',
    attributeUsed: 'varies',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-break_lift',
    name: 'Break or lift something',
    type: 'full',
    attributeUsed: 'strength',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-interact_tech',
    name: 'Interact with technology',
    type: 'full',
    attributeUsed: 'reason',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-stabilize',
    name: 'Stabilize a dying character',
    type: 'full',
    attributeUsed: 'reason',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-give_orders',
    name: 'Give orders',
    type: 'full',
    attributeUsed: 'presence',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-rally',
    name: 'Rally a broken character',
    type: 'full',
    attributeUsed: 'presence',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-recover_resolve',
    name: 'Recover Resolve',
    type: 'full',
    attributeUsed: 'presence',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-persuade',
    name: 'Persuade someone',
    type: 'full',
    attributeUsed: 'presence',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-save_bystanders',
    name: 'Save bystanders',
    type: 'full',
    attributeUsed: 'varies',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'full-fly_sky',
    name: 'Fly sky high or into orbit',
    type: 'full',
    attributeUsed: '-',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },

  
  {
    _id: 'quick-move_zone',
    name: 'Move into an adjacent zone',
    type: 'quick',
    attributeUsed: '-',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'quick-block_slugfest',
    name: 'Block a slugfest attack',
    type: 'quick',
    attributeUsed: 'fighting',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'quick-dodge_shooting',
    name: 'Dodge a shooting attack',
    type: 'quick',
    attributeUsed: 'agility',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'quick-pick_up',
    name: 'Pick up an item',
    type: 'quick',
    attributeUsed: '-',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'quick-scan_area',
    name: 'Scan an area for details',
    type: 'quick',
    attributeUsed: 'intuition',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'quick-action_banter',
    name: 'Action banter',
    type: 'quick',
    attributeUsed: 'presence',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'quick-start_vehicle',
    name: 'Start a vehicle',
    type: 'quick',
    attributeUsed: '-',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'quick-enter_exit_vehicle',
    name: 'Enter/exit a vehicle',
    type: 'quick',
    attributeUsed: '-',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'quick-handle_vehicle',
    name: 'Handle a vehicle',
    type: 'quick',
    attributeUsed: 'agility',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
  {
    _id: 'quick-use_item',
    name: 'Use item',
    type: 'quick',
    attributeUsed: 'varies',
    bonus: 0,
    range: '-',
    damage: '',
    description: '',
    specialFeatures: '',
    isDefault: true,
    isActive: true,
  },
];
